### ISSUE TITLE
CSRF Scanner extension is not working well  1.7.14 version of Burp.

### ISSUE THREAD

**Issue by v3rl** [ah8r/csrf#3]
Hi, 
CSRF Scanner extension  is unable to find CSRF issue passively and actively in test sites like demo.testfire.net.
 I ran passive scan and active scan both on the 2 form requests on the same site,  but it was unable to detect it.

system details:
Win2k8 64 bit.
java version 1.8.x

**Comment by ah8r** [comment]
Hi @vinaya470,

Can you give me an example of a page which the scanner fails to detect? Also, are you adding this site to the scope in Burp before scanning? This extension only works against sites you have defined in the scope.

**Comment by v3rl** [comment]
Thanks for the reply. 
demo.testfire.net site was under the scope. I added it and CSRF Scanner started detecting it. Sorry, but my bad, I might have missed it while reading the documentation , incase if mentioned there or so.
Just wanted to confirm lack of two features in the extension:
1. Would Like to skip GET request from getting included int he issues reported by this Scanner. 99% of the time , inclusion of GET request leads to lots of False positives , as,  it is against HTTP standard to use GET for State changing.
2.  This extension currently does not detect anti csrf token present in header. For Angular Js application , I would prefer putting the antiCSRF token in header instead of POST parameter.  SO, would like to add this feature.

**Comment by ah8r** [comment]
Hi @vinaya470,

Glad adding the site to scope worked out. As for your two feature suggestions:

1. I have a working update which allow you to select which HTTP methods you wish to scan, so that should fix the issue.

2. Can you link to some documentation for the Angular JS implementation, i.e. what it looks like. I believe this should be an easy fix.

**Comment by ah8r** [comment]
I've committed an update which adds checkboxes for common HTTP methods. You can deselect the "GET" checkbox and no GET requests will be scanned.

**Comment by ah8r** [comment]
As of commit 72c9a378439fdb19f364d3a879db6463fea4121c the extension now checks for tokens within HTTP headers.
