### ISSUE TITLE
Error when loading jar for Burp Extension

### ISSUE THREAD

**Issue by l50** [ah8r/csrf#9]
Pulled the jar directly from the repo, and got this when I added it to Burp Pro v1.7.26:
```
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.sue.a(Unknown Source)
	at burp.sue.<init>(Unknown Source)
	at burp.mn.a(Unknown Source)
	at burp.ooh.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ah8r** [comment]
I'm unable to reproduce. What version of Java are you using?

Have you tried compiling the source code along with the Burp Extender API and creating the JAR yourself?

BTW, the latest version of the code is in the BApp store now, if that's easier.

**Comment by ah8r** [comment]
Closing due to lack of comment.

**Comment by l50** [comment]
Apologies, I did not have this issue flagged as being watching this issue evidently.

```
java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
I will retry the new jar you've committed, and so long as the one in the bapp store stays up-to-date, that could definitely be a great way to go for me as well. 

Basically, I've been automating installing and maintaining useful burp extensions that I use regularly with ansible, and this is one of them, so thanks for contributing it.

I've had to compile a couple, which is fine as well. I figured if there was a release jar available, I'd take advantage.

**Comment by ah8r** [comment]
Let me know if the same issue occurs with the new JAR. I don't see any reason why it should not run, I'm compiling for Java 8 and the JAR should include all the package info.

I always make it a point to get the latest changes across to the BApp store version ASAP (it takes a few days).
